config/routes.rb
Rails.application.routes.draw do

  get "/" => "books#index"

  post "/books" => "books#create"
  get "/books/:id" => "books#show", as: :book

  get "/books/:id/edit" => "books#edit", as: :edit_book
  patch "/books/:id" => "books#update", as: :update_book
  delete "/books/:id" => "books#delete", as: :delete_book

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    render :index
  end


  def create
    @books = Book.all
    @book = Book.create(book_params)
    redirect_to "/books/#{@book.id}"
  end

  def show
    @book = Book.find(params["id"])
    render :show
  end

  def edit
    @book = Book.find(params["id"])
    render :edit
  end

  def update
    @book = Book.find(params["id"])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end

  def delete
    @book = Book.find(params["id"])
    @book.destroy
    redirect_to book_path
  end


   private def book_params
     params.require("book").permit(:title)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1><%= @book.title %> </h1>

<%= form_for @book, url: update_book_path(@book.id) do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
  <% end %>

<%= form_tag delete_book_path(id: @book.id), method: :delete do %>
<%= submit_tag "Remove"%>
<% end %>
  <%= link_to "Back to homepage", books_path %>
  <%= link_to "Back to #{@book.title}", book_path(id: @book.id) %>

app/views/books/index.html.erb
<h1> Books on Books </h1>


<table>
  <tbody>
    <% @books.each do |book| %>
    <tr>
    <td><%= link_to "#{book.title}", book_path(id: book.id)%></td>
    </tr>
    <% end %>
  </tbody>
</table>



<%= form_tag("/books", class: "") do %>
<%= text_field_tag "book[title]" %>
<%= submit_tag %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>


<%= link_to "Edit", edit_book_path %>

<%= link_to "Homepage", "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaceOfBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>